CREATE TABLE IF NOT EXISTS `EeAppAdmin` ( 
`Id` int(11) NOT NULL AUTO_INCREMENT, 
`AppId` INT  NULL ,
`UserId` INT  NULL ,
PRIMARY KEY (`Id`),
CONSTRAINT `EeAppApp_EeAppAdmin` FOREIGN KEY (`AppId`) REFERENCES `EeAppApp`(`Id`),
CONSTRAINT `ee_user_EeAppAdmin` FOREIGN KEY (`UserId`) REFERENCES `ee_user`(`Id`)
) ENGINE=InnoDB  DEFAULT CHARACTER SET `utf8`; 